Improve SEO page scan
apostrophecms/apostrophe-seo pull request #46
Opened 2021-02-17 15:47 UTC by ValJed

* Scan internal and external links
* Scan images to check alt attributes
* Scan Open graph title and description
* Implement design

If you want to try the feature, you can simply link the module inside any apostrophe project.

2021-02-17 16:26 UTC, boutell requested changes
Just one minor option name change. Good stuff.

2021-02-17 16:26 UTC, boutell commented on README.md
> +      minWordsNumber: 400
Let's make this `minWordsOnPage`

2021-02-17 16:26 UTC, boutell commented on lib/api.js
> +        which does not meet the minimum requirements of <strong>${minWordsNumber}</strong>.`
Minimum requirement, not requirements

2021-02-17 16:26 UTC, boutell commented on lib/api.js
> +      msg: `There are <strong>${totalWords}</strong> words on the page, which meets the minimum requirements of <strong>${minWordsNumber}</strong>.`
requirement, not requirements

2021-02-18 13:32 UTC, ValJed commented on README.md
> +      minWordsNumber: 400
Yup done !

2021-02-18 13:32 UTC, ValJed commented on lib/api.js
> +      msg: `There are <strong>${totalWords}</strong> words on the page, which meets the minimum requirements of <strong>${minWordsNumber}</strong>.`
Done

2021-02-18 13:35 UTC, ValJed commented on lib/api.js
> +        which does not meet the minimum requirements of <strong>${minWordsNumber}</strong>.`
Modified

2021-02-18 13:35 UTC, ValJed commented on lib/api.js
> +        which does not meet the minimum requirements of <strong>${minWordsNumber}</strong>.`
Fixed

2021-02-18 15:00 UTC, boutell approved these changes

2021-02-19 13:31 UTC, merged